### ISSUE TITLE
Update Offer Gaming

### ISSUE THREAD

**Issue by geggleto** [dapperlabs/cryptokitties-bounty-2#10]
### Description
Update offer is not subject to the same minimal increase mechanism as an outstanding out-bid offer. This presents an infinite defense mechanism where buy the current offer holder may prevent anyone from out-biding.

### Scenario
1. Player A makes an offer of Y to Kitty X
2. Player A scans the blockchain looking for additional out-bid offer (Z) on Kitty X by Player B.
3. When detected the Player incrementally offers (Z - the out-bid amount + 1 wei) - Y.
4. This then becomes a race via GAS COST; the motivation behind Player A is likely very high and thus they will likely use a very high gas-price and win the race.

### Impact
- Medium

### Reproduction
This is mostly a theory on how someone can prevent anyone else from bidding on a kitty.

### Fix
It should be much more expensive to update an offer. It should re-create an offer and invalidate your old offer.

**Comment by bradleymcallister97** [comment]
Hey @geggleto,

Thank you for the feedback. We understand that there could be scenarios where players can attempt to block/prevent another user from successfully creating an offer by scanning the blockchain.

These race conditions are rare and would only occur when the network is congested.

Closing now.
