### ISSUE TITLE
Missing typecast of offer.expiresAt variable from uint64 to uint256

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#11]
### Description
In bidderWithdrawFunds, uint256 expiresAt is assigned the value of offer.expiresAt. However, offer.expiresAt is a uint64, and should be explicitly typecast to a uint256.

### Scenario
Solidity requires an explicit typecast of a uint64 to a uint256 if assigning.

### Impact
In bidderWithdrawFunds, assignment of uint256 expiresAt from uint64 offer.expiresAt will fail.

### Reproduction
Observe the following line of code:

uint256 expiresAt = offer.expiresAt;

Note that it lacks an explicit typecast on the right side of the equals sign.

### Fix
In Offers.sol bidderWithdrawFunds function, change this line of code:

uint256 expiresAt = offer.expiresAt;

to this:

uint256 expiresAt = uint256(offer.expiresAt);

**Comment by zhangchiqing** [comment]
Hi @michaelKim4736 ,

Thanks for the feedback, which version of solidity compiler are you using? The latest version `0.4.24 ` doesn't require such explicit typecast anymore, unless I missed something.

We are able to compile the solidity code into the abi file as commited in the source code (https://github.com/dapperlabs/cryptokitties-bounty-2/blob/master/build/contracts/Offers.json).
