### ISSUE TITLE
Constructor initializes CFO and LostAndFound to 0x0

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#12]
### Description
The code assumes that CFO and Lost&Found are not 0x0 (see _newLostAndFound != address(0), etc.)

However, the contract begins with both CFO and Lost&Found being 0x0.

This means that "transfer" calls could indeed burn funds, if called before CFO and Lost&Found are set.

### Scenario
Since the Offers.sol constructor does not initialize lostAndFoundAddress and cfoAddress, these addresses will begin as 0x0. Yet functions exist that can transfer funds to cfoAddress/lostAndFoundAddress, meaning that these functions would burn the funds.

### Impact
Functions exist that transfer funds to CFO and Lost&Found. Since there exists a period of time where CFO and Lost&Found are 0x0, there is a dangerous period of time where functions exist that can transfer funds to 0x0.

### Reproduction
After Offers.sol is initialized and before setLostAndFound or setCFO are called, CFO and Lost&Found are 0x0.

### Fix
In constructor, add:

cfoAddress = msg.sender;
lostAndFoundAddress = msg.sender;

after setting CEO to msg.sender

**Comment by hwrdtm** [comment]
Thanks @michaelKim4736 for your feedback.

It's true that upon initialization, CFO and Lost&Found are unset, defaulted to `0x0`. However, `.transfer()` calls to these addresses are _only_ made in the `.withdrawTotalCFOEarnings()` and `.withdrawTotalLostAndFoundBalance()` functions, which are also available if `onlyCFO` and `onlyLostAndFound`, respectively. 

The `0x0` cannot call this, and hence no funds would be burnt.

In other functions such as `fulfillOffer`, the contract doesn't immediately `.transfer()` to CFO or LostAndFound – instead, their balances are kept in storage.

Closing now.
