### ISSUE TITLE
batchRemoveExpired has missing typecast from uint64 to uint256

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#13]
### Description
In batchRemoveExpired, uint256 expiresAt is assigned the value of offer.expiresAt. However, offer.expiresAt is a uint64, and should be explicitly typecast to a uint256.

### Scenario
Solidity requires an explicit typecast of a uint64 to a uint256 if assigning.

### Impact
In batchRemoveExpired, assignment of uint256 expiresAt from uint64 offer.expiresAt will fail.

### Reproduction
Observe the following line of code:

uint256 expiresAt = offer.expiresAt;

Note that it lacks an explicit typecast on the right side of the equals sign.

### Fix
In Offers.sol batchRemoveExpired function, change this line of code:

uint256 expiresAt = offer.expiresAt;

to this:

uint256 expiresAt = uint256(offer.expiresAt);

**Comment by geggleto** [comment]
expiresAt is uint64 in some places.

line 332: `offer.expiresAt = uint64(newExpiresAt);`
line 124: `uint64(newExpiresAt),

I believe both of these should also be casted to uint256

**Comment by michaelKim4736** [comment]
Thanks @geggleto , line 332 is actually correct as it is though. This is because the "offer" struct has a expiresAt property that is only uint64. When assigning a value to offer's expiresAt property, you must typecast it as uint64, as is currently done, otherwise you would overwrite an adjacent 192 bits.

The same applies to line 124, that is also correct as it is.

**Comment by flockonus** [comment]
Such cast is not required as it's converting from a smaller magnitude to a bigger one
