### ISSUE TITLE
institute safety measure for changing CEO, CFO, COO, lostandfound addresses

### ISSUE THREAD

**Issue by sunsetlover** [dapperlabs/cryptokitties-bounty-2#21]
### Description
Because of the idiosyncraties of sending transactions with geth, there is a risk of changing the CEO, CFO, COO, or lost and found address to an unintended and possibly nonexistent address. The blockchain is unforgiving to mistakes (i.e. the game breaking cat: 844006) so we should be as careful as possible to mitigate risks especially when the cost to do so is minimal. Given that you are already checking any change of address is not the all 0 address, my suggestion takes this a step further. In particular, I suggest you create a double check on chain.

### Scenario
See the first comment of this post for very real ways that geth can create a new address unintentionally: https://www.reddit.com/r/ethereum/comments/4a8c2h/geth_sent_the_transaction_to_the_wrong_address/ There are many other ways of geth unintentionally creating new addresses if you do not input or format an address correctly.

### Impact
If any of these addresses are changed to an unintended address, among many other impacts like losing control of some of the functionality of the contract, one of the larger impacts is that ether can be forever lost since the CFO cannot withdraw the earnings and the lost and found address cannot withdraw the lost funds. 

### Fix
Throughout this example, I'll focus on changing the COO address.

1) Create a public variable called `address tempCOOaddress`
2) When the contract constructor is called, set `tempCOOaddress` to `msg.sender`
3) Add a function that only the COO can call that modifies `tempCOOaddress` to a proposed new address.
4) Add a function that only the COO can call that changes the COO address to the `tempCOOaddress`. This should be the only way that the COO address can change. (Presumably this happens after someone double checks that `tempCOOaddress` does indeed have the right value.)

**Comment by hwrdtm** [comment]
Thanks @sunsetlover for your feedback! We have acknowledged it and will be taking it into consideration.

**Comment by hwrdtm** [comment]
We have come to a conclusion and do not plan to add anymore checks for setting these addresses.

Closing for now.
