### ISSUE TITLE
design flaw in bidding system that potentially allows attacker to bypass free market pricing

### ISSUE THREAD

**Issue by sunsetlover** [dapperlabs/cryptokitties-bounty-2#34]
### Description
An attacker can potentially get a cat for much **less** than another user is willing to offer.

This attack completely invalidates the whole point of `minimumOverbidPrice` unless you believe the unsuccessful fee is enough to deter someone.

(#10 talks about a similar issue. However, I believe the issue I bring up is fundamentally different. In #10, you could argue that the “free market” along with requiring a minimal change in new bids will push the price of the offer to a “fair price.” Front running are issues not unique to this specific bidding system, but an issue all throughout ethereum. However, the attack I describe here manipulates the “free market” price since someone else is willing to pay more).

### Scenario
1. A player submits an offer for a cat.
2. An attacker submits a slightly higher offer for this cat; cancels their offer; and then submits a new offer for much less. Note that this can all be performed in one transaction via an external contract so that the attacker has completely eliminated the possibility of getting their first higher offer fulfilled.
3. The first two steps can of course be repeated until one player no longer wishes to pay the unsuccessful auction fee potentially leaving the attacker as the final bid. 

### Impact
1. This can create a poor user experience for non-automated players.
2. This can create a poor user experience for the owner depending on how they get notified about offers. For instance, they may get an email that says there is an offer for 10 eth for their cat and they want to accept this offer. So they set their minimum acceptance price to 10 eth, but in the meantime the current bid is much lower so their transaction to fulfill the offer will fail.

### Fix
Subject to minimal code changes, I can think of one way to help fix this issue that does not hugely favor those with a lot of eth and those using automation (anymore than the blockchain already allows). In a nutshell, decide on some time horizon such that every time an active auction gets modified, the time horizon gets extended and the maximum offer ever made (active or not) during this time horizon is recorded. Ideally, the time horizon, would be a reasonable amount of time where the owner of the cat could see the offers.

Introduce a changeable state variable called `timeLimit.` In the `Offers` struct, add two new variables: `timer` and `maxBid`.

1. If an offer is made for a cat that does not have an active offer, set `tokenIdToOffer[cat].timer = now + timeLimit` and `tokenIdToOffer[cat].maxBid = msg.value`.
2. If an offer is updated and `now < tokenIdToOffer[cat].timer`, then set ``tokenIdToOffer[cat].maxBid = msg.value`.
3. If an offer is cancelled and `now < tokenIdToOffer[cat].timer`, then set `tokenIdToOffer[cat].timer = now + timeLimit`.
4. If an offer is created and `now < tokenIdToOffer[cat].timer`, among the other checks on `msg.value` to see if its a valid offer amount, include `msg.value > tokenIdToOffer[cat].maxBid`.

One pushback is that now an attacker with enough eth could “lock” a cat up (by offering a lot of eth and then cancelling their offer blocking anyone else to bid on this cat). However, at this point, the owner of the cat could just list their cat for sale so this is a non-issue.

### Additional Thoughts
I assume the purpose of the unsuccessful auction fee is to discourage such an attack or spamming. However, I highly doubt a small nominal fee would stop someone from performing this attack especially when its automation vs a human user. Again, this attack completely invalidates the whole point of `minimumOverbidPrice` unless again you believe the fee is enough to deter someone.

**Comment by TomLeeFounder** [comment]
You say that this would be a big problem unless `unsuccessfulFee` is enough to deter an Attacker. However, in the scenario you describe above, an attacker would pay more than `unsuccessfulFee` each time.

In step 2 of the **Scenario** section above, you say that the Attacker would overbid a competitor *and then cancel their bid*. Cancelling costs significantly more than `unsuccessfulFee`, since `unsuccessfulFee` is a flat fee, whereas the fee for cancelling is T - P, which scales linearly with the price of the cat offered. 

So the attack that you describe would cost significantly more, especially for higher value cats, making the attack less and less desirable as the price of the cat increases.

**Comment by sunsetlover** [comment]
@TomLeeFounder you are right. Thanks. Can't believe I glossed over the cancel fee part. 😅 Sounds like they thought this through already. Closing.
